spring:
  cloud:
    gateway:
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
          - Path=/api/customers/**
        - id: ms-bankcredit-credits
          uri: lb://ms-bankcredit
          predicates:
          - Path=/api/credits/**
        - id: ms-bankcredit-creditcards
          uri: lb://ms-bankcredit
          predicates:
          - Path=/api/creditcards/**
        - id: ms-bankaccount
          uri: lb://ms-bankaccount
          predicates:
          - Path=/api/bankaccount/**
        - id: ms-transaction
          uri: lb://ms-transaction
          predicates:
          - Path=/api/transactions/**
        - id: ms-bankaccount-debitcard
          uri: lb://ms-bankaccount
          predicates:
          - Path=/api/debitcards/**
        - id: ms-mobilewallet
          uri: lb://ms-mobilewallet
          predicates:
          - Path=/api/wallets/**
        - id: ms-customer-reports
          uri: lb://ms-customer
          predicates:
          - Path=/api/customers/reports/**
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: my-secret-key