spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mobilewallet
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  file:
    name: logs/app.log
server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    seriveUrl:
      defaultZone: http://localhost:8761/eureka
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ms-mobilewallet-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.ms_bankaccount.model
    topic:
      bank-account-request: "bank-account-request-topic"
      bank-account-response: "bank-account-response-topic"

