spring:
  data:
    monbodb:
      uri: mongodb://localhost:27017/mobilewallet
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
logging:
  file:
    name: logs/app.log
server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
  client:
    seriveUrl:
      defaultZone: http://localhost:8761/eureka

